# Proyecto de Machine Learning

## Predicción de Fallas Vehiculares

### Integrante
- Tu nombre

### Materia
Machine Learning

### Objetivo

Desarrollar un modelo de Machine Learning capaz de predecir si un vehículo presenta una falla utilizando el dataset proporcionado por el docente.

---

## Metodología

Este proyecto seguirá la metodología enseñada en el notebook **ML_Modulo_10_Pipeline_Completo_Seleccion_Modelos.ipynb**.

Etapas del proyecto:

1. Carga del dataset
2. Análisis exploratorio (EDA)
3. Limpieza de datos
4. Preprocesamiento
5. Entrenamiento de modelos
6. Comparación de modelos
7. Evaluación
8. Selección del mejor modelo
9. Guardado del modelo

In [2]:
# ============================================
# LIBRERÍAS DEL PROYECTO
# ============================================

import pandas as pd
import numpy as np

In [3]:
# ============================================
# CARGAR EL DATASET
# ============================================

df = pd.read_csv("../data/Dataset_fallas_vehiculares_bolivia (2).csv")

df.head()

,region,altitud_msnm,marca,tipo_vehiculo,año_fabricacion,antiguedad_años,kilometraje,ultimo_mantenimiento_dias,calidad_combustible,octanaje_estimado,...,temperatura_motor_c,nivel_aceite,presion_neumaticos_psi,bateria_voltaje,estado_frenos,filtro_aire,tipo_via,condicion_via,temperatura_ambiente_c,falla_vehiculo
0,Cochabamba,2335.0,Suzuki,Pickup,1989.0,36.0,432391.0,19.0,Degradada,78.8,...,94.9,Bajo,30.4,11.53,Bueno,Obstruido,Ruta Interdepartamental,Mala,1.2,1
1,Trinidad,68.0,Hyundai,Sedán,NaN,27.0,340315.0,108.0,Normal,85.4,...,97.6,Óptimo,35.8,12.16,Crítico,NaN,Carretera Pavimentada,muy_mala,16.2,1
2,Santa Cruz,474.0,suzuki,Camión,1987.0,38.0,454300.0,3.0,Contaminado,70.8,...,999.9,Óptimo,NaN,NaN,Crítico,Sucio,Ruta Interdepartamental,Regular,17.7,1
3,Sucre,2634.0,Mazda,NaN,2009.0,16.0,209152.0,27.0,Normal,89.2,...,92.4,Bajo,NaN,12.48,Regular,Sucio,Urbana,Regular,13.3,0
4,La Paz,3807.0,Mitsubishi,Camión,1998.0,27.0,399398.0,161.0,Degradada,80.4,...,121.2,Óptimo,34.6,NaN,Desgastado,Sucio,Carretera Pavimentada,Regular,22.3,1

In [4]:
# ============================================
# INFORMACIÓN GENERAL DEL DATASET
# ============================================

print("Número de filas y columnas:")
print(df.shape)

print("\nInformación del dataset:")
df.info()

Número de filas y columnas:
(10000, 21)

Información del dataset:
<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 21 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   region                     9900 non-null   str
 1   altitud_msnm               9700 non-null   float64
 2   marca                      9600 non-null   str
 3   tipo_vehiculo              9700 non-null   str
 4   año_fabricacion            9500 non-null   float64
 5   antiguedad_años            9500 non-null   float64
 6   kilometraje                9300 non-null   float64
 7   ultimo_mantenimiento_dias  9000 non-null   float64
 8   calidad_combustible        9200 non-null   str
 9   octanaje_estimado          8500 non-null   float64
 10  contaminacion_agua_ppm     8200 non-null   float64
 11  temperatura_motor_c        8800 non-null   float64
 12  nivel_aceite               9400 non-null   str
 13  presion_neumaticos_psi     9100 non-null   float64
 14  bateria_voltaje            9200 non-null   float64
 15  estado_frenos              9300 non-null   str
 16  filtro_aire                9500 non-null   str
 17  tipo_via                   9600 non-null   str
 18  condicion_via              9400 non-null   str
 19  temperatura_ambiente_c     9600 non-null   float64
 20  falla_vehiculo             10000 non-null  int64
dtypes: float64(11), int64(1), str(9)
memory usage: 1.6 MB

In [5]:
# ============================================
# ESTADÍSTICAS DESCRIPTIVAS
# ============================================

df.describe()

,altitud_msnm,año_fabricacion,antiguedad_años,kilometraje,ultimo_mantenimiento_dias,octanaje_estimado,contaminacion_agua_ppm,temperatura_motor_c,presion_neumaticos_psi,bateria_voltaje,temperatura_ambiente_c,falla_vehiculo
count,9700.000000,9500.000000,9500.000000,9.300000e+03,9000.000000,8500.000000,8200.000000,8800.000000,9100.000000,9200.000000,9600.000000,10000.000000
mean,2503.466389,2012.396000,25.050842,3.272868e+05,556.176417,85.733966,614.275008,106.093268,33.527108,14.431429,12.404656,0.610800
std,4352.199360,378.361285,10.164281,2.749358e+05,5535.313014,49.337082,6226.397276,88.127416,44.302478,43.557569,7.779979,0.487593
min,-4968.074318,0.000000,2.000000,-9.990039e+03,-493.604727,-47.223240,-974.563170,-49.695234,-49.598007,-99.335494,-8.000000,0.000000
25%,513.000000,1991.000000,17.000000,2.056922e+05,36.000000,79.100000,4.400000,88.600000,27.500000,11.500000,7.200000,0.000000
50%,2591.000000,1998.000000,27.000000,3.187960e+05,91.000000,84.600000,8.000000,97.500000,31.100000,11.980000,12.200000,1.000000
75%,3608.000000,2008.000000,34.000000,4.173152e+05,181.000000,87.700000,50.400000,106.300000,34.300000,12.480000,17.700000,1.000000
max,92547.161808,9999.000000,40.000000,4.956437e+06,97930.763058,979.801883,98273.342872,999.900000,985.975022,981.669797,38.800000,1.000000

In [6]:
# ============================================
# VALORES FALTANTES
# ============================================

df.isnull().sum()

region                        100
altitud_msnm                  300
marca                         400
tipo_vehiculo                 300
año_fabricacion               500
antiguedad_años               500
kilometraje                   700
ultimo_mantenimiento_dias    1000
calidad_combustible           800
octanaje_estimado            1500
contaminacion_agua_ppm       1800
temperatura_motor_c          1200
nivel_aceite                  600
presion_neumaticos_psi        900
bateria_voltaje               800
estado_frenos                 700
filtro_aire                   500
tipo_via                      400
condicion_via                 600
temperatura_ambiente_c        400
falla_vehiculo                  0
dtype: int64

In [7]:
# ============================================
# NOMBRES DE LAS COLUMNAS
# ============================================

df.columns

Index(['region', 'altitud_msnm', 'marca', 'tipo_vehiculo', 'año_fabricacion',
       'antiguedad_años', 'kilometraje', 'ultimo_mantenimiento_dias',
       'calidad_combustible', 'octanaje_estimado', 'contaminacion_agua_ppm',
       'temperatura_motor_c', 'nivel_aceite', 'presion_neumaticos_psi',
       'bateria_voltaje', 'estado_frenos', 'filtro_aire', 'tipo_via',
       'condicion_via', 'temperatura_ambiente_c', 'falla_vehiculo'],
      dtype='str')

In [8]:
# ============================================
# VALORES ÚNICOS DE CADA COLUMNA
# ============================================

for columna in df.columns:
    print(f"\n===== {columna} =====")
    print(df[columna].unique()[:10])

===== region =====
<StringArray>
['Cochabamba',   'Trinidad', 'Santa Cruz',      'Sucre',     'La Paz',
     'Tarija',     'Potosí',          nan,      'Oruro',     'Cobija']
Length: 10, dtype: str

===== altitud_msnm =====
[ 2335.          68.         474.        2634.        3807.
  3629.        3653.       -2837.690958  1982.         533.      ]

===== marca =====
<StringArray>
[    'Suzuki',    'Hyundai',     'suzuki',      'Mazda', 'Mitsubishi',
     'Toyota',  'Chevrolet',     'Nissan',       'Ford',          nan]
Length: 10, dtype: str

===== tipo_vehiculo =====
<StringArray>
[       'Pickup',         'Sedán',        'Camión',             nan,
 'Camioneta 4x4',  'camioneta4x4',       'Minibús',       'MiniBus',
        'Camion',           'SUV']
Length: 10, dtype: str

===== año_fabricacion =====
[1989.   nan 1987. 2009. 1998. 1997. 1985. 2011. 2008. 1986.]

===== antiguedad_años =====
[36. 27. 38. 16. 28. 40. 14. 17. 39. 30.]

===== kilometraje =====
[432391. 340315. 454300. 209152. 399398. 318530. 542561. 156302. 337668.
 355863.]

===== ultimo_mantenimiento_dias =====
[ 19. 108.   3.  27. 161.  42.  70. 231.   5.   2.]

===== calidad_combustible =====
<StringArray>
[  'Degradada',      'Normal', 'Contaminado',       'NORML',           nan,
 'CONTAMINADA', 'Contaminada',     'Normal ',      'normal',       'Norml']
Length: 10, dtype: str

===== octanaje_estimado =====
[78.8 85.4 70.8 89.2 80.4 80.1  nan 86.  76.5  0. ]

===== contaminacion_agua_ppm =====
[ 42.3   3.1   nan   4.3  48.3   3.8   2.1 109.4   5.   86.5]

===== temperatura_motor_c =====
[ 94.9  97.6 999.9  92.4 121.2  85.3   nan  91.3  81.8 110.2]

===== nivel_aceite =====
<StringArray>
[    'Bajo',   'Óptimo', 'Muy Bajo',     'bajo',   'Optimo',   'OPTIMO',
   'optimo',        nan,      'bjo', 'MUY BAJO']
Length: 10, dtype: str

===== presion_neumaticos_psi =====
[30.4 35.8  nan 34.6 32.  29.9 25.4 30.7 36.4 33.1]

===== bateria_voltaje =====
[11.53 12.16   nan 12.48 11.69 12.44 10.66 11.68 13.12 11.31]

===== estado_frenos =====
<StringArray>
[     'Bueno',    'Crítico',    'Regular', 'Desgastado',          nan,
      'BUENO',  'Desgastad',    'regular', 'desgastado',    'CRITICO']
Length: 10, dtype: str

===== filtro_aire =====
<StringArray>
['Obstruido',         nan,     'Sucio',    'Limpio', 'OBSTRUIDO', 'obstruido',
    'LIMPIO',     'Limpo',     'scuio',     'sucio']
Length: 10, dtype: str

===== tipo_via =====
<StringArray>
['Ruta Interdepartamental',   'Carretera Pavimentada',
                  'Urbana',        'Camino de Tierra',
                       nan]
Length: 5, dtype: str

===== condicion_via =====
<StringArray>
[    'Mala', 'muy_mala',  'Regular',        nan, 'Muy Mala', 'muy mala',
    'Buena', 'Muy mala',     'mala',      'mla']
Length: 10, dtype: str

===== temperatura_ambiente_c =====
[ 1.2 16.2 17.7 13.3 22.3 14.1  5.3  9.8 18.  13.1]

===== falla_vehiculo =====
[1 0]

In [9]:
# ============================================
# NOMBRES DE LAS COLUMNAS
# ============================================

print(df.columns)

Index(['region', 'altitud_msnm', 'marca', 'tipo_vehiculo', 'año_fabricacion',
       'antiguedad_años', 'kilometraje', 'ultimo_mantenimiento_dias',
       'calidad_combustible', 'octanaje_estimado', 'contaminacion_agua_ppm',
       'temperatura_motor_c', 'nivel_aceite', 'presion_neumaticos_psi',
       'bateria_voltaje', 'estado_frenos', 'filtro_aire', 'tipo_via',
       'condicion_via', 'temperatura_ambiente_c', 'falla_vehiculo'],
      dtype='str')

In [10]:
# ============================================
# TIPOS DE DATOS
# ============================================

print(df.dtypes)

region                           str
altitud_msnm                 float64
marca                            str
tipo_vehiculo                    str
año_fabricacion              float64
antiguedad_años              float64
kilometraje                  float64
ultimo_mantenimiento_dias    float64
calidad_combustible              str
octanaje_estimado            float64
contaminacion_agua_ppm       float64
temperatura_motor_c          float64
nivel_aceite                     str
presion_neumaticos_psi       float64
bateria_voltaje              float64
estado_frenos                    str
filtro_aire                      str
tipo_via                         str
condicion_via                    str
temperatura_ambiente_c       float64
falla_vehiculo                 int64
dtype: object

In [11]:
# ============================================
# VALORES ÚNICOS
# ============================================

for columna in df.columns:
    print(f"\n===== {columna} =====")
    print(df[columna].unique()[:10])

===== region =====
<StringArray>
['Cochabamba',   'Trinidad', 'Santa Cruz',      'Sucre',     'La Paz',
     'Tarija',     'Potosí',          nan,      'Oruro',     'Cobija']
Length: 10, dtype: str

===== altitud_msnm =====
[ 2335.          68.         474.        2634.        3807.
  3629.        3653.       -2837.690958  1982.         533.      ]

===== marca =====
<StringArray>
[    'Suzuki',    'Hyundai',     'suzuki',      'Mazda', 'Mitsubishi',
     'Toyota',  'Chevrolet',     'Nissan',       'Ford',          nan]
Length: 10, dtype: str

===== tipo_vehiculo =====
<StringArray>
[       'Pickup',         'Sedán',        'Camión',             nan,
 'Camioneta 4x4',  'camioneta4x4',       'Minibús',       'MiniBus',
        'Camion',           'SUV']
Length: 10, dtype: str

===== año_fabricacion =====
[1989.   nan 1987. 2009. 1998. 1997. 1985. 2011. 2008. 1986.]

===== antiguedad_años =====
[36. 27. 38. 16. 28. 40. 14. 17. 39. 30.]

===== kilometraje =====
[432391. 340315. 454300. 209152. 399398. 318530. 542561. 156302. 337668.
 355863.]

===== ultimo_mantenimiento_dias =====
[ 19. 108.   3.  27. 161.  42.  70. 231.   5.   2.]

===== calidad_combustible =====
<StringArray>
[  'Degradada',      'Normal', 'Contaminado',       'NORML',           nan,
 'CONTAMINADA', 'Contaminada',     'Normal ',      'normal',       'Norml']
Length: 10, dtype: str

===== octanaje_estimado =====
[78.8 85.4 70.8 89.2 80.4 80.1  nan 86.  76.5  0. ]

===== contaminacion_agua_ppm =====
[ 42.3   3.1   nan   4.3  48.3   3.8   2.1 109.4   5.   86.5]

===== temperatura_motor_c =====
[ 94.9  97.6 999.9  92.4 121.2  85.3   nan  91.3  81.8 110.2]

===== nivel_aceite =====
<StringArray>
[    'Bajo',   'Óptimo', 'Muy Bajo',     'bajo',   'Optimo',   'OPTIMO',
   'optimo',        nan,      'bjo', 'MUY BAJO']
Length: 10, dtype: str

===== presion_neumaticos_psi =====
[30.4 35.8  nan 34.6 32.  29.9 25.4 30.7 36.4 33.1]

===== bateria_voltaje =====
[11.53 12.16   nan 12.48 11.69 12.44 10.66 11.68 13.12 11.31]

===== estado_frenos =====
<StringArray>
[     'Bueno',    'Crítico',    'Regular', 'Desgastado',          nan,
      'BUENO',  'Desgastad',    'regular', 'desgastado',    'CRITICO']
Length: 10, dtype: str

===== filtro_aire =====
<StringArray>
['Obstruido',         nan,     'Sucio',    'Limpio', 'OBSTRUIDO', 'obstruido',
    'LIMPIO',     'Limpo',     'scuio',     'sucio']
Length: 10, dtype: str

===== tipo_via =====
<StringArray>
['Ruta Interdepartamental',   'Carretera Pavimentada',
                  'Urbana',        'Camino de Tierra',
                       nan]
Length: 5, dtype: str

===== condicion_via =====
<StringArray>
[    'Mala', 'muy_mala',  'Regular',        nan, 'Muy Mala', 'muy mala',
    'Buena', 'Muy mala',     'mala',      'mla']
Length: 10, dtype: str

===== temperatura_ambiente_c =====
[ 1.2 16.2 17.7 13.3 22.3 14.1  5.3  9.8 18.  13.1]

===== falla_vehiculo =====
[1 0]

In [12]:
# ============================================
# REGISTROS DUPLICADOS
# ============================================

duplicados = df.duplicated().sum()

print(f"Registros duplicados: {duplicados}")

Registros duplicados: 0

In [13]:
# ============================================
# COLUMNAS DEL DATASET
# ============================================

for columna in df.columns:
    print(columna)

region
altitud_msnm
marca
tipo_vehiculo
año_fabricacion
antiguedad_años
kilometraje
ultimo_mantenimiento_dias
calidad_combustible
octanaje_estimado
contaminacion_agua_ppm
temperatura_motor_c
nivel_aceite
presion_neumaticos_psi
bateria_voltaje
estado_frenos
filtro_aire
tipo_via
condicion_via
temperatura_ambiente_c
falla_vehiculo

In [14]:
df["falla_vehiculo"].value_counts()

falla_vehiculo
1    6108
0    3892
Name: count, dtype: int64

In [15]:
# ============================================
# PORCENTAJE DE VALORES FALTANTES
# ============================================

porcentaje_nan = (df.isnull().sum() / len(df)) * 100

porcentaje_nan = porcentaje_nan.sort_values(ascending=False)

print(porcentaje_nan)

contaminacion_agua_ppm       18.0
octanaje_estimado            15.0
temperatura_motor_c          12.0
ultimo_mantenimiento_dias    10.0
presion_neumaticos_psi        9.0
bateria_voltaje               8.0
calidad_combustible           8.0
estado_frenos                 7.0
kilometraje                   7.0
condicion_via                 6.0
nivel_aceite                  6.0
año_fabricacion               5.0
antiguedad_años               5.0
filtro_aire                   5.0
tipo_via                      4.0
temperatura_ambiente_c        4.0
marca                         4.0
altitud_msnm                  3.0
tipo_vehiculo                 3.0
region                        1.0
falla_vehiculo                0.0
dtype: float64

In [16]:
# ============================================
# COLUMNAS CON VALORES FALTANTES
# ============================================

nan = porcentaje_nan[porcentaje_nan > 0]

print(nan)

contaminacion_agua_ppm       18.0
octanaje_estimado            15.0
temperatura_motor_c          12.0
ultimo_mantenimiento_dias    10.0
presion_neumaticos_psi        9.0
bateria_voltaje               8.0
calidad_combustible           8.0
estado_frenos                 7.0
kilometraje                   7.0
condicion_via                 6.0
nivel_aceite                  6.0
año_fabricacion               5.0
antiguedad_años               5.0
filtro_aire                   5.0
tipo_via                      4.0
temperatura_ambiente_c        4.0
marca                         4.0
altitud_msnm                  3.0
tipo_vehiculo                 3.0
region                        1.0
dtype: float64

In [17]:
# ============================================
# VEHÍCULOS CON AÑO INVÁLIDO
# ============================================

df[df["año_fabricacion"] == 9999]

,region,altitud_msnm,marca,tipo_vehiculo,año_fabricacion,antiguedad_años,kilometraje,ultimo_mantenimiento_dias,calidad_combustible,octanaje_estimado,...,temperatura_motor_c,nivel_aceite,presion_neumaticos_psi,bateria_voltaje,estado_frenos,filtro_aire,tipo_via,condicion_via,temperatura_ambiente_c,falla_vehiculo
510,Tarija,1844.0,Chevrolet,SUV,9999.0,9.0,117689.0,144.0,Degradada,84.9,...,80.7,Bajo,NaN,12.24,Regular,Limpio,Ruta Interdepartamental,Mala,7.6,1
1018,Santa Cruz,159.0,Suzuki,camion,9999.0,NaN,154961.0,394.0,Normal,NaN,...,91.5,Óptimo,29.300000,12.40,Crítico,Limpio,Camino de Tierra,Mala,15.2,0
1316,Cochabamba,2739.0,Hyundai,Sedn,9999.0,38.0,566366.0,33.0,Normal,92.6,...,108.1,Óptimo,692.959607,11.83,Desgastado,Limpio,Carretera Pavimentada,Buena,17.3,1
1845,Oruro,3804.0,Ford,Sedán,9999.0,37.0,392818.0,243.0,Contaminada,76.0,...,111.7,Bajo,27.500000,12.03,Regular,obstruido,Ruta Interdepartamental,REGULAR,22.9,1
2552,Santa Cruz,553.0,Toyota,Sedán,9999.0,8.0,80189.0,NaN,Degradada,84.6,...,91.8,Óptimo,27.500000,NaN,Regular,Sucio,Urbana,Mala,14.9,1
2777,La Paz,3667.0,Kia,Minibús,9999.0,12.0,111703.0,5.0,Normal,90.4,...,116.1,Óptimo,35.000000,12.74,Regular,Sucio,Urbana,Regular,11.2,0
2999,Santa Cruz,360.0,Hyundai,SUV,9999.0,12.0,110017.0,77.0,Normal,89.2,...,95.9,Óptimo,34.400000,13.87,Bueno,Sucio,Urbana,Buena,6.4,1
3315,Tarija,NaN,Chevrolet,Camioneta 4x4,9999.0,33.0,319554.0,55.0,Degradada,78.5,...,108.9,Óptimo,25.600000,12.36,Desgastado,limpio,Urbana,MALA,23.1,1
4315,La Paz,3575.0,KIA,Sedán,9999.0,26.0,310446.0,126.0,Normal,88.2,...,100.9,Bajo,32.200000,12.89,Crítico,Obstruido,Camino de Tierra,mala,-3.0,1
4403,Cochabamba,2619.0,Mitsubishi,Minibús,9999.0,21.0,211376.0,30.0,Normal,86.2,...,91.0,Óptimo,NaN,12.65,NaN,OBSTRUIDO,Urbana,Muy Mala,18.2,1
4869,Santa Cruz,433.0,Hyundai,Minibús,9999.0,32.0,506294.0,132.0,Contaminada,NaN,...,101.4,Muy Bajo,27.500000,12.98,Regular,Limpio,Carretera Pavimentada,Muy Mala,20.5,1
4975,Cochabamba,2360.0,Suzuki,NaN,9999.0,28.0,333378.0,8.0,Normal,86.4,...,110.5,Óptimo,26.200000,12.90,Crítico,Sucio,Carretera Pavimentada,regular,15.1,1
5234,Cochabamba,2535.0,Chevrolet,Camioneta 4x4,9999.0,21.0,283619.0,112.0,Degradada,81.3,...,96.0,Muy bajo,32.300000,12.30,Regular,Limpio,Urbana,Muy Mala,4.0,0
5406,Trinidad,164.0,Suzuki,SUV,9999.0,33.0,521325.0,59.0,Normal,83.6,...,115.6,Óptimo,34.100000,11.60,Desgastado,Limpio,Carretera Pavimentada,Muy Mala,19.8,1
6812,La Paz,3878.0,Kia,SEDÁN,9999.0,36.0,530664.0,116.0,Normal,86.5,...,97.9,muy_bajo,36.700000,12.21,Desgastado,NaN,Camino de Tierra,Buena,24.0,1
7843,Cochabamba,2601.0,Hyundai,Camioneta 4x4,9999.0,26.0,312343.0,21.0,Normal,86.7,...,108.8,NaN,35.200000,11.78,Bueno,Sucio,Urbana,NaN,14.7,1
8422,Oruro,3712.0,Ford,Camioneta 4x4,9999.0,32.0,410341.0,64.0,Normal,89.0,...,79.9,Óptimo,NaN,12.04,Desgastado,Sucio,Urbana,Buena,9.1,0
8481,Oruro,3760.0,Honda,Minibús,9999.0,16.0,218692.0,93.0,Contaminada,75.8,...,NaN,Muy Bajo,36.300000,11.71,Bueno,Sucio,Urbana,Mala,9.8,1
9152,La Paz,4004.0,Honda,SUV,9999.0,11.0,113290.0,90.0,Degradada,81.0,...,101.5,Óptimo,40.600000,11.36,Bueno,Sucio,Carretera Pavimentada,Regular,6.9,1
9432,Santa Cruz,434.0,Suzuki,Camioneta 4x4,9999.0,13.0,175279.0,64.0,Degradada,81.9,...,82.1,Óptimo,NaN,11.75,Regular,Limpio,Camino de Tierra,Buena,9.3,0

In [18]:
# ============================================
# PORCENTAJE DE VALORES FALTANTES
# ============================================

porcentaje_nan = (df.isnull().sum() / len(df)) * 100

porcentaje_nan = porcentaje_nan.sort_values(ascending=False)

print(porcentaje_nan)

contaminacion_agua_ppm       18.0
octanaje_estimado            15.0
temperatura_motor_c          12.0
ultimo_mantenimiento_dias    10.0
presion_neumaticos_psi        9.0
bateria_voltaje               8.0
calidad_combustible           8.0
estado_frenos                 7.0
kilometraje                   7.0
condicion_via                 6.0
nivel_aceite                  6.0
año_fabricacion               5.0
antiguedad_años               5.0
filtro_aire                   5.0
tipo_via                      4.0
temperatura_ambiente_c        4.0
marca                         4.0
altitud_msnm                  3.0
tipo_vehiculo                 3.0
region                        1.0
falla_vehiculo                0.0
dtype: float64

In [19]:
# ============================================
# COLUMNAS CON VALORES FALTANTES
# ============================================

nan = porcentaje_nan[porcentaje_nan > 0]

print(nan)

contaminacion_agua_ppm       18.0
octanaje_estimado            15.0
temperatura_motor_c          12.0
ultimo_mantenimiento_dias    10.0
presion_neumaticos_psi        9.0
bateria_voltaje               8.0
calidad_combustible           8.0
estado_frenos                 7.0
kilometraje                   7.0
condicion_via                 6.0
nivel_aceite                  6.0
año_fabricacion               5.0
antiguedad_años               5.0
filtro_aire                   5.0
tipo_via                      4.0
temperatura_ambiente_c        4.0
marca                         4.0
altitud_msnm                  3.0
tipo_vehiculo                 3.0
region                        1.0
dtype: float64

In [20]:
# ============================================
# REGISTROS CON AÑO INVÁLIDO
# ============================================

df[df["año_fabricacion"] > 2026]

,region,altitud_msnm,marca,tipo_vehiculo,año_fabricacion,antiguedad_años,kilometraje,ultimo_mantenimiento_dias,calidad_combustible,octanaje_estimado,...,temperatura_motor_c,nivel_aceite,presion_neumaticos_psi,bateria_voltaje,estado_frenos,filtro_aire,tipo_via,condicion_via,temperatura_ambiente_c,falla_vehiculo
364,Trinidad,0.0,Mitsubishi,SUV,2086.0,25.0,2.925000e+05,30627.391992,Normal,NaN,...,101.500000,Muy Bajo,24.800000,11.78,Crítico,Sucio,NaN,buena,17.0,0
510,Tarija,1844.0,Chevrolet,SUV,9999.0,9.0,1.176890e+05,144.000000,Degradada,84.9,...,80.700000,Bajo,NaN,12.24,Regular,Limpio,Ruta Interdepartamental,Mala,7.6,1
528,La Paz,3373.0,Ford,Sedán,2057.0,29.0,3.352240e+05,45.000000,NORML,NaN,...,109.000000,Óptimo,34.200000,11.28,Desgastado,sucio,Carretera Pavimentada,Mala,5.1,1
726,La Paz,3589.0,hyundai,Camioneta 4x4,2081.0,39.0,0.000000e+00,169.000000,CONTAMINADO,72.0,...,73.900000,Muy Bajo,39.600000,11.87,Bueno,Limpio,Camino de Tierra,Mala,12.4,1
1018,Santa Cruz,159.0,Suzuki,camion,9999.0,NaN,1.549610e+05,394.000000,Normal,NaN,...,91.500000,Óptimo,29.300000,12.40,Crítico,Limpio,Camino de Tierra,Mala,15.2,0
1081,La Paz,3845.0,NaN,Minibús,2082.0,32.0,NaN,539.000000,Normal,84.9,...,220.486506,Muy Bajo,26.900000,11.50,Desgastado,Sucio,Carretera Pavimentada,NaN,-1.4,1
1316,Cochabamba,2739.0,Hyundai,Sedn,9999.0,38.0,5.663660e+05,33.000000,Normal,92.6,...,108.100000,Óptimo,692.959607,11.83,Desgastado,Limpio,Carretera Pavimentada,Buena,17.3,1
1338,La Paz,3514.0,TOYOTA,SUV,2079.0,40.0,5.296160e+05,31.000000,Normal,81.7,...,122.600000,Óptimo,21.900000,12.15,Regular,Obstruido,Carretera Pavimentada,Buena,14.0,1
1638,Cobija,97.0,Chevrolet,Minibús,2097.0,39.0,4.130480e+06,338.000000,Normal,89.3,...,83.900000,Bajo,39.600000,NaN,Desgastado,scuio,Camino de Tierra,Regular,11.1,1
1766,Santa Cruz,399.0,NaN,SUV,2076.0,19.0,NaN,90.000000,Degragada,84.4,...,105.100000,Óptimo,35.300000,13.13,Desgastado,Obstruido,Carretera Pavimentada,Muy Mala,17.6,0
1845,Oruro,3804.0,Ford,Sedán,9999.0,37.0,3.928180e+05,243.000000,Contaminada,76.0,...,111.700000,Bajo,27.500000,12.03,Regular,obstruido,Ruta Interdepartamental,REGULAR,22.9,1
1921,La Paz,3699.0,CHEVROLET,SUV,2063.0,26.0,2.982280e+05,9.000000,Normal,91.7,...,121.200000,Bajo,34.500000,11.47,Regular,Sucio,Ruta Interdepartamental,Regular,-8.0,0
2334,La Paz,3416.0,Kia,Camioneta 4x4,2098.0,30.0,3.267360e+05,105.000000,Normal,86.8,...,97.700000,NaN,37.200000,10.97,Regular,Limpio,Carretera Pavimentada,Regular,6.0,1
2459,Cochabamba,2576.0,Chevrolet,SUV,2059.0,22.0,3.187480e+05,289.000000,Normal,86.3,...,98.700000,Bajo,32.500000,11.57,NaN,Sucio,Urbana,Mala,21.0,1
2552,Santa Cruz,553.0,Toyota,Sedán,9999.0,8.0,8.018900e+04,NaN,Degradada,84.6,...,91.800000,Óptimo,27.500000,NaN,Regular,Sucio,Urbana,Mala,14.9,1
2777,La Paz,3667.0,Kia,Minibús,9999.0,12.0,1.117030e+05,5.000000,Normal,90.4,...,116.100000,Óptimo,35.000000,12.74,Regular,Sucio,Urbana,Regular,11.2,0
2907,Oruro,3704.0,Hyundai,Camion,2060.0,38.0,5.594320e+05,125.000000,Contaminada,72.3,...,97.100000,Bajo,26.300000,10.88,Bueno,Sucio,Ruta Interdepartamental,NaN,10.4,1
2999,Santa Cruz,360.0,Hyundai,SUV,9999.0,12.0,1.100170e+05,77.000000,Normal,89.2,...,95.900000,Óptimo,34.400000,13.87,Bueno,Sucio,Urbana,Buena,6.4,1
3315,Tarija,NaN,Chevrolet,Camioneta 4x4,9999.0,33.0,3.195540e+05,55.000000,Degradada,78.5,...,108.900000,Óptimo,25.600000,12.36,Desgastado,limpio,Urbana,MALA,23.1,1
3669,Cochabamba,2457.0,Mitsubishi,Camión,2091.0,12.0,1.508200e+05,30.000000,Degradada,NaN,...,NaN,Óptimo,35.500000,13.08,Regular,LIMPIO,Carretera Pavimentada,Regular,19.0,0
3917,Potosí,4030.0,Nissan,Camioneta 4x4,2073.0,34.0,4.531350e+05,128.000000,Normal,85.5,...,93.300000,Óptimo,36.800000,13.23,Crítico,NaN,Urbana,Regular,18.1,0
4074,Santa Cruz,NaN,Ford,Sedán,2055.0,28.0,3.702370e+05,81.000000,Norml,90.2,...,102.700000,Óptimo,34.100000,11.89,Crítico,Sucio,Urbana,Muy Mala,16.3,1
4167,La Paz,3589.0,Kia,Camioneta 4x4,2057.0,37.0,5.764000e+05,191.000000,Contaminado,71.7,...,99.700000,NaN,32.900000,12.44,Desgastado,Limpio,Ruta Interdepartamental,Mala,19.9,1
4315,La Paz,3575.0,KIA,Sedán,9999.0,26.0,3.104460e+05,126.000000,Normal,88.2,...,100.900000,Bajo,32.200000,12.89,Crítico,Obstruido,Camino de Tierra,mala,-3.0,1
4323,Cochabamba,2625.0,Mitsubishi,Camioneta 4x4,2088.0,31.0,4.368490e+05,125.000000,normal,88.8,...,100.400000,Óptimo,38.200000,NaN,Desgastado,Limpio,Camino de Tierra,Mala,8.9,0
4403,Cochabamba,2619.0,Mitsubishi,Minibús,9999.0,21.0,2.113760e+05,30.000000,Normal,86.2,...,91.000000,Óptimo,NaN,12.65,NaN,OBSTRUIDO,Urbana,Muy Mala,18.2,1
4869,Santa Cruz,433.0,Hyundai,Minibús,9999.0,32.0,5.062940e+05,132.000000,Contaminada,NaN,...,101.400000,Muy Bajo,27.500000,12.98,Regular,Limpio,Carretera Pavimentada,Muy Mala,20.5,1
4897,Potosí,3872.0,honda,Sedán,2099.0,7.0,7.387500e+04,31.000000,Normal,NaN,...,88.400000,Óptimo,32.100000,13.00,NaN,Obstruido,Ruta Interdepartamental,Muy Mala,5.4,0
4964,Cochabamba,2529.0,Hyundai,SUV,2051.0,32.0,4.207010e+05,65.000000,Contaminada,73.3,...,101.600000,Óptimo,NaN,12.11,Desgastado,Sucio,Urbana,NaN,13.5,1
4975,Cochabamba,2360.0,Suzuki,NaN,9999.0,28.0,3.333780e+05,8.000000,Normal,86.4,...,110.500000,Óptimo,26.200000,12.90,Crítico,Sucio,Carretera Pavimentada,regular,15.1,1
5234,Cochabamba,2535.0,Chevrolet,Camioneta 4x4,9999.0,21.0,2.836190e+05,112.000000,Degradada,81.3,...,96.000000,Muy bajo,32.300000,12.30,Regular,Limpio,Urbana,Muy Mala,4.0,0
5406,Trinidad,164.0,Suzuki,SUV,9999.0,33.0,5.213250e+05,59.000000,Normal,83.6,...,115.600000,Óptimo,34.100000,11.60,Desgastado,Limpio,Carretera Pavimentada,Muy Mala,19.8,1
6364,Cochabamba,2608.0,Nissan,SUV,2097.0,18.0,1.814260e+05,30.000000,Normal,NaN,...,100.600000,Optimo,30.200000,12.65,Bueno,Limpio,Camino de Tierra,mla,17.4,0
6523,La Paz,3588.0,Kia,Sedán,2074.0,8.0,7.259500e+04,62.000000,Normal,88.2,...,98.100000,Óptimo,32.400000,13.06,regular,Sucio,Ruta Interdepartamental,Mala,10.7,0
6812,La Paz,3878.0,Kia,SEDÁN,9999.0,36.0,5.306640e+05,116.000000,Normal,86.5,...,97.900000,muy_bajo,36.700000,12.21,Desgastado,NaN,Camino de Tierra,Buena,24.0,1
6976,Santa Cruz,550.0,Ford,Camión,2058.0,26.0,3.160930e+05,158.000000,NaN,67.7,...,77.100000,Bajo,38.600000,12.34,Crítico,Sucio,Camino de Tierra,Muy Mala,14.7,1
7742,Santa Cruz,334.0,Mazda,Camioneta 4x4,2052.0,32.0,4.073660e+05,41.000000,Degradada,76.9,...,84.500000,optimo,29.300000,12.26,Desgastado,Obstruído,Carretera Pavimentada,Muy Mala,18.5,0
7843,Cochabamba,2601.0,Hyundai,Camioneta 4x4,9999.0,26.0,3.123430e+05,21.000000,Normal,86.7,...,108.800000,NaN,35.200000,11.78,Bueno,Sucio,Urbana,NaN,14.7,1
8197,Potosí,4339.0,Mazda,NaN,2075.0,24.0,2.260320e+05,151.000000,Normal,86.8,...,95.500000,Óptimo,35.800000,NaN,Desgastado,Sucio,Camino de Tierra,Muy Mala,9.4,0
8317,Santa Cruz,259.0,Toyota,S.U.V,2084.0,40.0,3.817340e+05,20.000000,Normal,80.6,...,95.100000,Bajo,43.000000,11.96,Regular,Obstruido,Camino de Tierra,Regular,17.5,0
8327,Santa Cruz,413.0,Mitsubishi,Minibús,2075.0,37.0,5.147460e+05,8.000000,Normal,91.5,...,96.800000,Óptimo,27.000000,10.63,NaN,Sucio,Camino de Tierra,Muy Mala,13.5,1
8422,Oruro,3712.0,Ford,Camioneta 4x4,9999.0,32.0,4.103410e+05,64.000000,Normal,89.0,...,79.900000,Óptimo,NaN,12.04,Desgastado,Sucio,Urbana,Buena,9.1,0
8481,Oruro,3760.0,Honda,Minibús,9999.0,16.0,2.186920e+05,93.000000,Contaminada,75.8,...,NaN,Muy Bajo,36.300000,11.71,Bueno,Sucio,Urbana,Mala,9.8,1
8618,La Paz,3618.0,Mitsubishi,Camioneta 4x4,2077.0,NaN,2.879840e+05,NaN,Contaminada,72.6,...,96.300000,bjo,26.800000,12.56,Critico,Obstruido,Urbana,Mala,-3.8,1
9118,Trinidad,263.0,Kia,Pickup,2062.0,26.0,2.965910e+05,65.000000,Normal,83.3,...,77.300000,NaN,42.300000,11.14,Desgastado,Limpio,Camino de Tierra,Mala,20.5,1
9152,La Paz,4004.0,Honda,SUV,9999.0,11.0,1.132900e+05,90.000000,Degradada,81.0,...,101.500000,Óptimo,40.600000,11.36,Bueno,Sucio,Carretera Pavimentada,Regular,6.9,1
9432,Santa Cruz,434.0,Suzuki,Camioneta 4x4,9999.0,13.0,1.752790e+05,64.000000,Degradada,81.9,...,82.100000,Óptimo,NaN,11.75,Regular,Limpio,Camino de Tierra,Buena,9.3,0
9466,Santa Cruz,359.0,Hyundai,Sedán,2050.0,24.0,2.768880e+05,NaN,Degradada,82.8,...,79.600000,Óptimo,32.200000,11.70,REGULAR,Obstruido,Ruta Interdepartamental,Mala,17.8,0

In [21]:
# ============================================
# KILOMETRAJES NEGATIVOS
# ============================================

df[df["kilometraje"] < 0]

,region,altitud_msnm,marca,tipo_vehiculo,año_fabricacion,antiguedad_años,kilometraje,ultimo_mantenimiento_dias,calidad_combustible,octanaje_estimado,...,temperatura_motor_c,nivel_aceite,presion_neumaticos_psi,bateria_voltaje,estado_frenos,filtro_aire,tipo_via,condicion_via,temperatura_ambiente_c,falla_vehiculo
789,Trinidad,259.0,Toyota,SUV,2022.0,3.0,-7927.212852,53.0,Normal,84.6,...,91.3,Óptimo,32.1,12.98,NaN,Obstruido,Ruta Interdepartamental,Buena,22.4,1
845,Cochabamba,2454.0,Mazda,CAMIONETA 4X4,2010.0,15.0,-2643.733046,79.0,Contaminada,70.2,...,87.3,Óptimo,30.3,13.30,Desgastado,Sucio,Urbana,Buena,15.9,1
888,La Paz,3742.0,Chevrolet,SEDAN,2007.0,18.0,-9353.757869,24.0,Normal,NaN,...,94.7,Óptimo,29.8,11.38,Regular,NaN,Carretera Pavimentada,Buena,-0.3,0
1000,La Paz,3623.0,Suzuki,SUV,1987.0,38.0,-1204.534735,223.0,Degradada,83.0,...,114.5,Bajo,21.9,11.29,Desgastado,Sucio,Urbana,Muy Mala,17.4,1
1147,Tarija,1857.0,Suzuki,SUV,2010.0,15.0,-2283.096993,53.0,Normal,83.8,...,NaN,Muy Bajo,34.6,12.28,Regular,Limpo,Ruta Interdepartamental,Muy Mala,5.6,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8961,Cochabamba,2693.0,Nissan,Sedán,1998.0,27.0,-6151.712139,NaN,Normal,88.3,...,127.5,NaN,41.0,12.15,Desgastado,Obstruido,Carretera Pavimentada,Regular,19.8,1
9012,La Paz,NaN,Mazda,camioneta 4x4,NaN,39.0,-1273.614681,NaN,Normal,87.4,...,116.9,Bajo,26.7,11.65,Desgastado,Sucio,Ruta Interdepartamental,Regular,13.1,1
9224,Santa Cruz,89.0,Chevrolet,Camioneta 4X4,1994.0,31.0,-8235.156958,158.0,Contaminada,80.8,...,79.1,Bajo,33.4,12.60,regular,Obstruido,Urbana,Mala,7.4,1
9320,La Paz,3836.0,Hyundai,Pickup,1986.0,39.0,-3962.280766,93.0,Normal,84.8,...,132.7,bjo,34.5,12.62,NaN,Limpio,Carretera Pavimentada,Regular,2.9,0
9836,Santa Cruz,654.0,Toyota,Pickup,2004.0,21.0,-8482.678685,190.0,Normal,89.2,...,95.4,Muy Bajo,28.9,13.42,Desgastado,Obstruido,Urbana,Regular,28.9,1

In [22]:
# ============================================
# TEMPERATURAS FUERA DE RANGO
# ============================================

df[df["temperatura_motor_c"] < 0]

,region,altitud_msnm,marca,tipo_vehiculo,año_fabricacion,antiguedad_años,kilometraje,ultimo_mantenimiento_dias,calidad_combustible,octanaje_estimado,...,temperatura_motor_c,nivel_aceite,presion_neumaticos_psi,bateria_voltaje,estado_frenos,filtro_aire,tipo_via,condicion_via,temperatura_ambiente_c,falla_vehiculo
343,Cochabamba,2759.0,Mitsubishi,Sedán,1993.0,32.0,371985.0,99.0,Normal,NaN,...,-24.903450,Bajo,NaN,11.90,Desgastado,NaN,Urbana,Regular,9.9,1
374,La Paz,3471.0,Onda,Minibús,2003.0,22.0,309571.0,NaN,Normal,NaN,...,-31.427088,Óptimo,35.2,NaN,Regular,Limpio,Camino de Tierra,Regular,16.7,0
431,Santa Cruz,588.0,Nissan,Camión,1993.0,32.0,361815.0,100.0,Normal,88.8,...,-25.559914,Bajo,31.2,12.55,Regular,Obstruido,Camino de Tierra,Regular,14.3,0
439,NaN,3614.0,Honda,Camioneta 4x4,2005.0,20.0,227403.0,82.0,Normal,86.9,...,-33.956661,Óptimo,24.9,12.57,Regular,Obstruido,Carretera Pavimentada,Regular,11.2,0
459,La Paz,3551.0,KIA,Sedán,1995.0,30.0,366440.0,16.0,Normal,87.4,...,-37.701049,Bajo,24.5,12.00,Desgastado,Obstruido,Urbana,Mala,11.2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9522,Trinidad,228.0,Honda,Camioneta 4x4,1991.0,34.0,404663.0,450.0,Normal,80.7,...,-21.072748,Muy Bajo,28.7,12.09,Regular,Sucio,Urbana,Muy Mala,14.0,1
9690,Trinidad,402.0,Mazda,SUV,2010.0,15.0,187388.0,119.0,Norml,90.3,...,-16.364359,Bajo,24.3,12.21,Bueno,Sucio,Ruta Interdepartamental,Mala,18.9,0
9827,Sucre,2923.0,Honda,Camioneta 4x4,1995.0,30.0,404525.0,48.0,Normal,84.9,...,-28.208541,Muy Bajo,31.5,13.51,Desgastado,Sucio,Carretera Pavimentada,Regular,10.5,1
9952,Cochabamba,2525.0,Chevrolet,Minibús,1999.0,26.0,403921.0,56.0,Degradada,78.4,...,-23.481866,Óptimo,32.2,12.34,Desgastado,Sucio,Urbana,Regular,9.3,1
9974,Cochabamba,NaN,Mazda,NaN,1987.0,NaN,400019.0,NaN,Degradada,85.5,...,-21.324261,Bajo,40.1,10.98,Crítico,SUCIO,Ruta Interdepartamental,Regular,13.0,1

In [23]:
# ============================================
# PORCENTAJE DE VALORES FALTANTES
# ============================================

porcentaje_nan = (df.isnull().sum() / len(df)) * 100

porcentaje_nan = porcentaje_nan.sort_values(ascending=False)

print(porcentaje_nan)

contaminacion_agua_ppm       18.0
octanaje_estimado            15.0
temperatura_motor_c          12.0
ultimo_mantenimiento_dias    10.0
presion_neumaticos_psi        9.0
bateria_voltaje               8.0
calidad_combustible           8.0
estado_frenos                 7.0
kilometraje                   7.0
condicion_via                 6.0
nivel_aceite                  6.0
año_fabricacion               5.0
antiguedad_años               5.0
filtro_aire                   5.0
tipo_via                      4.0
temperatura_ambiente_c        4.0
marca                         4.0
altitud_msnm                  3.0
tipo_vehiculo                 3.0
region                        1.0
falla_vehiculo                0.0
dtype: float64

In [24]:
# ============================================
# AÑOS INVÁLIDOS
# ============================================

df[df["año_fabricacion"] > 2026]

,region,altitud_msnm,marca,tipo_vehiculo,año_fabricacion,antiguedad_años,kilometraje,ultimo_mantenimiento_dias,calidad_combustible,octanaje_estimado,...,temperatura_motor_c,nivel_aceite,presion_neumaticos_psi,bateria_voltaje,estado_frenos,filtro_aire,tipo_via,condicion_via,temperatura_ambiente_c,falla_vehiculo
364,Trinidad,0.0,Mitsubishi,SUV,2086.0,25.0,2.925000e+05,30627.391992,Normal,NaN,...,101.500000,Muy Bajo,24.800000,11.78,Crítico,Sucio,NaN,buena,17.0,0
510,Tarija,1844.0,Chevrolet,SUV,9999.0,9.0,1.176890e+05,144.000000,Degradada,84.9,...,80.700000,Bajo,NaN,12.24,Regular,Limpio,Ruta Interdepartamental,Mala,7.6,1
528,La Paz,3373.0,Ford,Sedán,2057.0,29.0,3.352240e+05,45.000000,NORML,NaN,...,109.000000,Óptimo,34.200000,11.28,Desgastado,sucio,Carretera Pavimentada,Mala,5.1,1
726,La Paz,3589.0,hyundai,Camioneta 4x4,2081.0,39.0,0.000000e+00,169.000000,CONTAMINADO,72.0,...,73.900000,Muy Bajo,39.600000,11.87,Bueno,Limpio,Camino de Tierra,Mala,12.4,1
1018,Santa Cruz,159.0,Suzuki,camion,9999.0,NaN,1.549610e+05,394.000000,Normal,NaN,...,91.500000,Óptimo,29.300000,12.40,Crítico,Limpio,Camino de Tierra,Mala,15.2,0
1081,La Paz,3845.0,NaN,Minibús,2082.0,32.0,NaN,539.000000,Normal,84.9,...,220.486506,Muy Bajo,26.900000,11.50,Desgastado,Sucio,Carretera Pavimentada,NaN,-1.4,1
1316,Cochabamba,2739.0,Hyundai,Sedn,9999.0,38.0,5.663660e+05,33.000000,Normal,92.6,...,108.100000,Óptimo,692.959607,11.83,Desgastado,Limpio,Carretera Pavimentada,Buena,17.3,1
1338,La Paz,3514.0,TOYOTA,SUV,2079.0,40.0,5.296160e+05,31.000000,Normal,81.7,...,122.600000,Óptimo,21.900000,12.15,Regular,Obstruido,Carretera Pavimentada,Buena,14.0,1
1638,Cobija,97.0,Chevrolet,Minibús,2097.0,39.0,4.130480e+06,338.000000,Normal,89.3,...,83.900000,Bajo,39.600000,NaN,Desgastado,scuio,Camino de Tierra,Regular,11.1,1
1766,Santa Cruz,399.0,NaN,SUV,2076.0,19.0,NaN,90.000000,Degragada,84.4,...,105.100000,Óptimo,35.300000,13.13,Desgastado,Obstruido,Carretera Pavimentada,Muy Mala,17.6,0
1845,Oruro,3804.0,Ford,Sedán,9999.0,37.0,3.928180e+05,243.000000,Contaminada,76.0,...,111.700000,Bajo,27.500000,12.03,Regular,obstruido,Ruta Interdepartamental,REGULAR,22.9,1
1921,La Paz,3699.0,CHEVROLET,SUV,2063.0,26.0,2.982280e+05,9.000000,Normal,91.7,...,121.200000,Bajo,34.500000,11.47,Regular,Sucio,Ruta Interdepartamental,Regular,-8.0,0
2334,La Paz,3416.0,Kia,Camioneta 4x4,2098.0,30.0,3.267360e+05,105.000000,Normal,86.8,...,97.700000,NaN,37.200000,10.97,Regular,Limpio,Carretera Pavimentada,Regular,6.0,1
2459,Cochabamba,2576.0,Chevrolet,SUV,2059.0,22.0,3.187480e+05,289.000000,Normal,86.3,...,98.700000,Bajo,32.500000,11.57,NaN,Sucio,Urbana,Mala,21.0,1
2552,Santa Cruz,553.0,Toyota,Sedán,9999.0,8.0,8.018900e+04,NaN,Degradada,84.6,...,91.800000,Óptimo,27.500000,NaN,Regular,Sucio,Urbana,Mala,14.9,1
2777,La Paz,3667.0,Kia,Minibús,9999.0,12.0,1.117030e+05,5.000000,Normal,90.4,...,116.100000,Óptimo,35.000000,12.74,Regular,Sucio,Urbana,Regular,11.2,0
2907,Oruro,3704.0,Hyundai,Camion,2060.0,38.0,5.594320e+05,125.000000,Contaminada,72.3,...,97.100000,Bajo,26.300000,10.88,Bueno,Sucio,Ruta Interdepartamental,NaN,10.4,1
2999,Santa Cruz,360.0,Hyundai,SUV,9999.0,12.0,1.100170e+05,77.000000,Normal,89.2,...,95.900000,Óptimo,34.400000,13.87,Bueno,Sucio,Urbana,Buena,6.4,1
3315,Tarija,NaN,Chevrolet,Camioneta 4x4,9999.0,33.0,3.195540e+05,55.000000,Degradada,78.5,...,108.900000,Óptimo,25.600000,12.36,Desgastado,limpio,Urbana,MALA,23.1,1
3669,Cochabamba,2457.0,Mitsubishi,Camión,2091.0,12.0,1.508200e+05,30.000000,Degradada,NaN,...,NaN,Óptimo,35.500000,13.08,Regular,LIMPIO,Carretera Pavimentada,Regular,19.0,0
3917,Potosí,4030.0,Nissan,Camioneta 4x4,2073.0,34.0,4.531350e+05,128.000000,Normal,85.5,...,93.300000,Óptimo,36.800000,13.23,Crítico,NaN,Urbana,Regular,18.1,0
4074,Santa Cruz,NaN,Ford,Sedán,2055.0,28.0,3.702370e+05,81.000000,Norml,90.2,...,102.700000,Óptimo,34.100000,11.89,Crítico,Sucio,Urbana,Muy Mala,16.3,1
4167,La Paz,3589.0,Kia,Camioneta 4x4,2057.0,37.0,5.764000e+05,191.000000,Contaminado,71.7,...,99.700000,NaN,32.900000,12.44,Desgastado,Limpio,Ruta Interdepartamental,Mala,19.9,1
4315,La Paz,3575.0,KIA,Sedán,9999.0,26.0,3.104460e+05,126.000000,Normal,88.2,...,100.900000,Bajo,32.200000,12.89,Crítico,Obstruido,Camino de Tierra,mala,-3.0,1
4323,Cochabamba,2625.0,Mitsubishi,Camioneta 4x4,2088.0,31.0,4.368490e+05,125.000000,normal,88.8,...,100.400000,Óptimo,38.200000,NaN,Desgastado,Limpio,Camino de Tierra,Mala,8.9,0
4403,Cochabamba,2619.0,Mitsubishi,Minibús,9999.0,21.0,2.113760e+05,30.000000,Normal,86.2,...,91.000000,Óptimo,NaN,12.65,NaN,OBSTRUIDO,Urbana,Muy Mala,18.2,1
4869,Santa Cruz,433.0,Hyundai,Minibús,9999.0,32.0,5.062940e+05,132.000000,Contaminada,NaN,...,101.400000,Muy Bajo,27.500000,12.98,Regular,Limpio,Carretera Pavimentada,Muy Mala,20.5,1
4897,Potosí,3872.0,honda,Sedán,2099.0,7.0,7.387500e+04,31.000000,Normal,NaN,...,88.400000,Óptimo,32.100000,13.00,NaN,Obstruido,Ruta Interdepartamental,Muy Mala,5.4,0
4964,Cochabamba,2529.0,Hyundai,SUV,2051.0,32.0,4.207010e+05,65.000000,Contaminada,73.3,...,101.600000,Óptimo,NaN,12.11,Desgastado,Sucio,Urbana,NaN,13.5,1
4975,Cochabamba,2360.0,Suzuki,NaN,9999.0,28.0,3.333780e+05,8.000000,Normal,86.4,...,110.500000,Óptimo,26.200000,12.90,Crítico,Sucio,Carretera Pavimentada,regular,15.1,1
5234,Cochabamba,2535.0,Chevrolet,Camioneta 4x4,9999.0,21.0,2.836190e+05,112.000000,Degradada,81.3,...,96.000000,Muy bajo,32.300000,12.30,Regular,Limpio,Urbana,Muy Mala,4.0,0
5406,Trinidad,164.0,Suzuki,SUV,9999.0,33.0,5.213250e+05,59.000000,Normal,83.6,...,115.600000,Óptimo,34.100000,11.60,Desgastado,Limpio,Carretera Pavimentada,Muy Mala,19.8,1
6364,Cochabamba,2608.0,Nissan,SUV,2097.0,18.0,1.814260e+05,30.000000,Normal,NaN,...,100.600000,Optimo,30.200000,12.65,Bueno,Limpio,Camino de Tierra,mla,17.4,0
6523,La Paz,3588.0,Kia,Sedán,2074.0,8.0,7.259500e+04,62.000000,Normal,88.2,...,98.100000,Óptimo,32.400000,13.06,regular,Sucio,Ruta Interdepartamental,Mala,10.7,0
6812,La Paz,3878.0,Kia,SEDÁN,9999.0,36.0,5.306640e+05,116.000000,Normal,86.5,...,97.900000,muy_bajo,36.700000,12.21,Desgastado,NaN,Camino de Tierra,Buena,24.0,1
6976,Santa Cruz,550.0,Ford,Camión,2058.0,26.0,3.160930e+05,158.000000,NaN,67.7,...,77.100000,Bajo,38.600000,12.34,Crítico,Sucio,Camino de Tierra,Muy Mala,14.7,1
7742,Santa Cruz,334.0,Mazda,Camioneta 4x4,2052.0,32.0,4.073660e+05,41.000000,Degradada,76.9,...,84.500000,optimo,29.300000,12.26,Desgastado,Obstruído,Carretera Pavimentada,Muy Mala,18.5,0
7843,Cochabamba,2601.0,Hyundai,Camioneta 4x4,9999.0,26.0,3.123430e+05,21.000000,Normal,86.7,...,108.800000,NaN,35.200000,11.78,Bueno,Sucio,Urbana,NaN,14.7,1
8197,Potosí,4339.0,Mazda,NaN,2075.0,24.0,2.260320e+05,151.000000,Normal,86.8,...,95.500000,Óptimo,35.800000,NaN,Desgastado,Sucio,Camino de Tierra,Muy Mala,9.4,0
8317,Santa Cruz,259.0,Toyota,S.U.V,2084.0,40.0,3.817340e+05,20.000000,Normal,80.6,...,95.100000,Bajo,43.000000,11.96,Regular,Obstruido,Camino de Tierra,Regular,17.5,0
8327,Santa Cruz,413.0,Mitsubishi,Minibús,2075.0,37.0,5.147460e+05,8.000000,Normal,91.5,...,96.800000,Óptimo,27.000000,10.63,NaN,Sucio,Camino de Tierra,Muy Mala,13.5,1
8422,Oruro,3712.0,Ford,Camioneta 4x4,9999.0,32.0,4.103410e+05,64.000000,Normal,89.0,...,79.900000,Óptimo,NaN,12.04,Desgastado,Sucio,Urbana,Buena,9.1,0
8481,Oruro,3760.0,Honda,Minibús,9999.0,16.0,2.186920e+05,93.000000,Contaminada,75.8,...,NaN,Muy Bajo,36.300000,11.71,Bueno,Sucio,Urbana,Mala,9.8,1
8618,La Paz,3618.0,Mitsubishi,Camioneta 4x4,2077.0,NaN,2.879840e+05,NaN,Contaminada,72.6,...,96.300000,bjo,26.800000,12.56,Critico,Obstruido,Urbana,Mala,-3.8,1
9118,Trinidad,263.0,Kia,Pickup,2062.0,26.0,2.965910e+05,65.000000,Normal,83.3,...,77.300000,NaN,42.300000,11.14,Desgastado,Limpio,Camino de Tierra,Mala,20.5,1
9152,La Paz,4004.0,Honda,SUV,9999.0,11.0,1.132900e+05,90.000000,Degradada,81.0,...,101.500000,Óptimo,40.600000,11.36,Bueno,Sucio,Carretera Pavimentada,Regular,6.9,1
9432,Santa Cruz,434.0,Suzuki,Camioneta 4x4,9999.0,13.0,1.752790e+05,64.000000,Degradada,81.9,...,82.100000,Óptimo,NaN,11.75,Regular,Limpio,Camino de Tierra,Buena,9.3,0
9466,Santa Cruz,359.0,Hyundai,Sedán,2050.0,24.0,2.768880e+05,NaN,Degradada,82.8,...,79.600000,Óptimo,32.200000,11.70,REGULAR,Obstruido,Ruta Interdepartamental,Mala,17.8,0

In [26]:
# ============================================
# KILOMETRAJES NEGATIVOS
# ============================================

df[df["kilometraje"] < 0]

,region,altitud_msnm,marca,tipo_vehiculo,año_fabricacion,antiguedad_años,kilometraje,ultimo_mantenimiento_dias,calidad_combustible,octanaje_estimado,...,temperatura_motor_c,nivel_aceite,presion_neumaticos_psi,bateria_voltaje,estado_frenos,filtro_aire,tipo_via,condicion_via,temperatura_ambiente_c,falla_vehiculo
789,Trinidad,259.0,Toyota,SUV,2022.0,3.0,-7927.212852,53.0,Normal,84.6,...,91.3,Óptimo,32.1,12.98,NaN,Obstruido,Ruta Interdepartamental,Buena,22.4,1
845,Cochabamba,2454.0,Mazda,CAMIONETA 4X4,2010.0,15.0,-2643.733046,79.0,Contaminada,70.2,...,87.3,Óptimo,30.3,13.30,Desgastado,Sucio,Urbana,Buena,15.9,1
888,La Paz,3742.0,Chevrolet,SEDAN,2007.0,18.0,-9353.757869,24.0,Normal,NaN,...,94.7,Óptimo,29.8,11.38,Regular,NaN,Carretera Pavimentada,Buena,-0.3,0
1000,La Paz,3623.0,Suzuki,SUV,1987.0,38.0,-1204.534735,223.0,Degradada,83.0,...,114.5,Bajo,21.9,11.29,Desgastado,Sucio,Urbana,Muy Mala,17.4,1
1147,Tarija,1857.0,Suzuki,SUV,2010.0,15.0,-2283.096993,53.0,Normal,83.8,...,NaN,Muy Bajo,34.6,12.28,Regular,Limpo,Ruta Interdepartamental,Muy Mala,5.6,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8961,Cochabamba,2693.0,Nissan,Sedán,1998.0,27.0,-6151.712139,NaN,Normal,88.3,...,127.5,NaN,41.0,12.15,Desgastado,Obstruido,Carretera Pavimentada,Regular,19.8,1
9012,La Paz,NaN,Mazda,camioneta 4x4,NaN,39.0,-1273.614681,NaN,Normal,87.4,...,116.9,Bajo,26.7,11.65,Desgastado,Sucio,Ruta Interdepartamental,Regular,13.1,1
9224,Santa Cruz,89.0,Chevrolet,Camioneta 4X4,1994.0,31.0,-8235.156958,158.0,Contaminada,80.8,...,79.1,Bajo,33.4,12.60,regular,Obstruido,Urbana,Mala,7.4,1
9320,La Paz,3836.0,Hyundai,Pickup,1986.0,39.0,-3962.280766,93.0,Normal,84.8,...,132.7,bjo,34.5,12.62,NaN,Limpio,Carretera Pavimentada,Regular,2.9,0
9836,Santa Cruz,654.0,Toyota,Pickup,2004.0,21.0,-8482.678685,190.0,Normal,89.2,...,95.4,Muy Bajo,28.9,13.42,Desgastado,Obstruido,Urbana,Regular,28.9,1

In [25]:
# ============================================
# TEMPERATURAS INVÁLIDAS
# ============================================

df[df["temperatura_motor_c"] < 0]

,region,altitud_msnm,marca,tipo_vehiculo,año_fabricacion,antiguedad_años,kilometraje,ultimo_mantenimiento_dias,calidad_combustible,octanaje_estimado,...,temperatura_motor_c,nivel_aceite,presion_neumaticos_psi,bateria_voltaje,estado_frenos,filtro_aire,tipo_via,condicion_via,temperatura_ambiente_c,falla_vehiculo
343,Cochabamba,2759.0,Mitsubishi,Sedán,1993.0,32.0,371985.0,99.0,Normal,NaN,...,-24.903450,Bajo,NaN,11.90,Desgastado,NaN,Urbana,Regular,9.9,1
374,La Paz,3471.0,Onda,Minibús,2003.0,22.0,309571.0,NaN,Normal,NaN,...,-31.427088,Óptimo,35.2,NaN,Regular,Limpio,Camino de Tierra,Regular,16.7,0
431,Santa Cruz,588.0,Nissan,Camión,1993.0,32.0,361815.0,100.0,Normal,88.8,...,-25.559914,Bajo,31.2,12.55,Regular,Obstruido,Camino de Tierra,Regular,14.3,0
439,NaN,3614.0,Honda,Camioneta 4x4,2005.0,20.0,227403.0,82.0,Normal,86.9,...,-33.956661,Óptimo,24.9,12.57,Regular,Obstruido,Carretera Pavimentada,Regular,11.2,0
459,La Paz,3551.0,KIA,Sedán,1995.0,30.0,366440.0,16.0,Normal,87.4,...,-37.701049,Bajo,24.5,12.00,Desgastado,Obstruido,Urbana,Mala,11.2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9522,Trinidad,228.0,Honda,Camioneta 4x4,1991.0,34.0,404663.0,450.0,Normal,80.7,...,-21.072748,Muy Bajo,28.7,12.09,Regular,Sucio,Urbana,Muy Mala,14.0,1
9690,Trinidad,402.0,Mazda,SUV,2010.0,15.0,187388.0,119.0,Norml,90.3,...,-16.364359,Bajo,24.3,12.21,Bueno,Sucio,Ruta Interdepartamental,Mala,18.9,0
9827,Sucre,2923.0,Honda,Camioneta 4x4,1995.0,30.0,404525.0,48.0,Normal,84.9,...,-28.208541,Muy Bajo,31.5,13.51,Desgastado,Sucio,Carretera Pavimentada,Regular,10.5,1
9952,Cochabamba,2525.0,Chevrolet,Minibús,1999.0,26.0,403921.0,56.0,Degradada,78.4,...,-23.481866,Óptimo,32.2,12.34,Desgastado,Sucio,Urbana,Regular,9.3,1
9974,Cochabamba,NaN,Mazda,NaN,1987.0,NaN,400019.0,NaN,Degradada,85.5,...,-21.324261,Bajo,40.1,10.98,Crítico,SUCIO,Ruta Interdepartamental,Regular,13.0,1

In [27]:
# ============================================
# CORREGIR AÑOS INVÁLIDOS
# ============================================

import numpy as np

df.loc[df["año_fabricacion"] > 2026, "año_fabricacion"] = np.nan

print("Años inválidos corregidos.")

Años inválidos corregidos.

In [28]:
# ============================================
# CORREGIR KILOMETRAJES NEGATIVOS
# ============================================

df.loc[df["kilometraje"] < 0, "kilometraje"] = np.nan

print("Kilometrajes corregidos.")

Kilometrajes corregidos.

In [29]:
# ============================================
# CORREGIR TEMPERATURAS NEGATIVAS
# ============================================

df.loc[df["temperatura_motor_c"] < 0, "temperatura_motor_c"] = np.nan

print("Temperaturas corregidas.")

Temperaturas corregidas.

In [30]:
# ============================================
# RELLENAR COLUMNAS NUMÉRICAS
# ============================================

columnas_numericas = df.select_dtypes(include=["int64", "float64"]).columns

for columna in columnas_numericas:
    df[columna] = df[columna].fillna(df[columna].median())

In [31]:
# ============================================
# RELLENAR COLUMNAS CATEGÓRICAS
# ============================================

columnas_texto = df.select_dtypes(include=["object"]).columns

for columna in columnas_texto:
    df[columna] = df[columna].fillna(df[columna].mode()[0])

C:\Users\zasor\AppData\Local\Temp\ipykernel_17856\2005799209.py:5: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  columnas_texto = df.select_dtypes(include=["object"]).columns

In [32]:
# ============================================
# VERIFICACIÓN FINAL
# ============================================

print(df.isnull().sum())

region                       0
altitud_msnm                 0
marca                        0
tipo_vehiculo                0
año_fabricacion              0
antiguedad_años              0
kilometraje                  0
ultimo_mantenimiento_dias    0
calidad_combustible          0
octanaje_estimado            0
contaminacion_agua_ppm       0
temperatura_motor_c          0
nivel_aceite                 0
presion_neumaticos_psi       0
bateria_voltaje              0
estado_frenos                0
filtro_aire                  0
tipo_via                     0
condicion_via                0
temperatura_ambiente_c       0
falla_vehiculo               0
dtype: int64

In [33]:
# ============================================
# LIBRERÍAS PARA EL PREPROCESAMIENTO
# ============================================

from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

In [34]:
# ============================================
# CODIFICAR VARIABLES CATEGÓRICAS
# ============================================

label_encoders = {}

columnas_texto = df.select_dtypes(include=["object"]).columns

for columna in columnas_texto:
    
    le = LabelEncoder()

    df[columna] = le.fit_transform(df[columna])

    label_encoders[columna] = le

print("Variables categóricas codificadas correctamente.")

Variables categóricas codificadas correctamente.

C:\Users\zasor\AppData\Local\Temp\ipykernel_17856\3112005879.py:7: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  columnas_texto = df.select_dtypes(include=["object"]).columns

In [35]:
# ============================================
# TIPOS DE DATOS
# ============================================

print(df.dtypes)

region                         int64
altitud_msnm                 float64
marca                          int64
tipo_vehiculo                  int64
año_fabricacion              float64
antiguedad_años              float64
kilometraje                  float64
ultimo_mantenimiento_dias    float64
calidad_combustible            int64
octanaje_estimado            float64
contaminacion_agua_ppm       float64
temperatura_motor_c          float64
nivel_aceite                   int64
presion_neumaticos_psi       float64
bateria_voltaje              float64
estado_frenos                  int64
filtro_aire                    int64
tipo_via                       int64
condicion_via                  int64
temperatura_ambiente_c       float64
falla_vehiculo                 int64
dtype: object

In [36]:
# ============================================
# SEPARAR VARIABLES
# ============================================

X = df.drop("falla_vehiculo", axis=1)

y = df["falla_vehiculo"]

print(X.shape)

print(y.shape)

(10000, 20)
(10000,)

In [37]:
# ============================================
# TRAIN TEST SPLIT
# ============================================

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

print("Entrenamiento:", X_train.shape)

print("Prueba:", X_test.shape)

Entrenamiento: (8000, 20)
Prueba: (2000, 20)

In [38]:
# ============================================
# MODELO 1
# REGRESIÓN LOGÍSTICA
# ============================================

from sklearn.linear_model import LogisticRegression

from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

In [39]:
# ============================================
# ENTRENAR MODELO
# ============================================

modelo_lr = LogisticRegression(max_iter=1000)

modelo_lr.fit(X_train, y_train)

c:\Users\zasor\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 1000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=1000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression(max_iter=1000)

In [40]:
# ============================================
# PREDICCIONES
# ============================================

y_pred_lr = modelo_lr.predict(X_test)

In [41]:
# ============================================
# ACCURACY
# ============================================

accuracy_lr = accuracy_score(y_test, y_pred_lr)

print("Accuracy:", accuracy_lr)

Accuracy: 0.634

In [42]:
# ============================================
# MATRIZ DE CONFUSIÓN
# ============================================

print(confusion_matrix(y_test, y_pred_lr))

[[ 222  553]
 [ 179 1046]]

In [43]:
# ============================================
# REPORTE
# ============================================

print(classification_report(y_test, y_pred_lr))

              precision    recall  f1-score   support

           0       0.55      0.29      0.38       775
           1       0.65      0.85      0.74      1225

    accuracy                           0.63      2000
   macro avg       0.60      0.57      0.56      2000
weighted avg       0.62      0.63      0.60      2000

In [45]:
# ============================================
# MODELO 2
# DECISION TREE
# ============================================

from sklearn.tree import DecisionTreeClassifier

In [46]:
modelo_dt = DecisionTreeClassifier(random_state=42)

modelo_dt.fit(X_train, y_train)

DecisionTreeClassifier(random_state=42)

In [47]:
y_pred_dt = modelo_dt.predict(X_test)

In [48]:
accuracy_dt = accuracy_score(y_test, y_pred_dt)

print("Accuracy Decision Tree:", accuracy_dt)

Accuracy Decision Tree: 0.5615

In [49]:
print(confusion_matrix(y_test, y_pred_dt))

[[350 425]
 [452 773]]

In [50]:
print(confusion_matrix(y_test, y_pred_dt))

[[350 425]
 [452 773]]

In [51]:
print(classification_report(y_test, y_pred_dt))

              precision    recall  f1-score   support

           0       0.44      0.45      0.44       775
           1       0.65      0.63      0.64      1225

    accuracy                           0.56      2000
   macro avg       0.54      0.54      0.54      2000
weighted avg       0.56      0.56      0.56      2000

In [52]:
from sklearn.ensemble import RandomForestClassifier

modelo_rf = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

modelo_rf.fit(X_train, y_train)

y_pred_rf = modelo_rf.predict(X_test)

accuracy_rf = accuracy_score(y_test, y_pred_rf)

print("Accuracy Random Forest:", accuracy_rf)

print(confusion_matrix(y_test, y_pred_rf))

print(classification_report(y_test, y_pred_rf))

Accuracy Random Forest: 0.6535
[[311 464]
 [229 996]]
              precision    recall  f1-score   support

           0       0.58      0.40      0.47       775
           1       0.68      0.81      0.74      1225

    accuracy                           0.65      2000
   macro avg       0.63      0.61      0.61      2000
weighted avg       0.64      0.65      0.64      2000

In [53]:
from sklearn.svm import SVC

modelo_svm = SVC()

modelo_svm.fit(X_train, y_train)

y_pred_svm = modelo_svm.predict(X_test)

accuracy_svm = accuracy_score(y_test, y_pred_svm)

print("Accuracy SVM:", accuracy_svm)

print(confusion_matrix(y_test, y_pred_svm))

print(classification_report(y_test, y_pred_svm))

Accuracy SVM: 0.626
[[ 105  670]
 [  78 1147]]
              precision    recall  f1-score   support

           0       0.57      0.14      0.22       775
           1       0.63      0.94      0.75      1225

    accuracy                           0.63      2000
   macro avg       0.60      0.54      0.49      2000
weighted avg       0.61      0.63      0.55      2000

In [54]:
import pandas as pd

resultados = pd.DataFrame({
    "Modelo": [
        "Logistic Regression",
        "Decision Tree",
        "Random Forest",
        "SVM"
    ],
    "Accuracy": [
        accuracy_lr,
        accuracy_dt,
        accuracy_rf,
        accuracy_svm
    ]
})

resultados = resultados.sort_values(
    by="Accuracy",
    ascending=False
)

print(resultados)

                Modelo  Accuracy
2        Random Forest    0.6535
0  Logistic Regression    0.6340
3                  SVM    0.6260
1        Decision Tree    0.5615

In [56]:
import joblib

joblib.dump(modelo_rf, "../modelo/modelo.pkl")

print("Modelo Random Forest guardado correctamente.")

Modelo Random Forest guardado correctamente.

In [57]:
joblib.dump(label_encoders, "../modelo/label_encoders.pkl")

print("Encoders guardados correctamente.")

Encoders guardados correctamente.

In [58]:
modelo_final = modelo_rf

In [59]:
import joblib

joblib.dump(modelo_final, "../modelo/modelo.pkl")
joblib.dump(label_encoders, "../modelo/label_encoders.pkl")

print("Modelo y encoders guardados correctamente.")

Modelo y encoders guardados correctamente.